language: go
go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - tip
before_install:
    sudo pip install codecov
script:
  - go test
after_success:
    codecov --token=$CODECOV_TOKEN
notifications:
  email:
    recipients:
      - montana@montanaflynn.me
    on_success: change
    on_failure: always
