language: go
go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - tip
before_install:
  - go get golang.org/x/tools/cmd/cover
script:
  - go test -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - montana@montanaflynn.me
    on_success: change
    on_failure: always
sudo: false
